version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: scoter-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scoter_db

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - scoter-network

volumes:
  db_data:

networks:
  scoter-network:
